### ISSUE TITLE
Log in with Facebook

### ISSUE THREAD

**Issue by macbookandrew** [UltraCart/my_account#13]
The client I’m building a site for would like her customers to be able to log in to their account using Facebook.

I've got the customer portal set up and working with standard login, but am trying to figure out how to use FB to log in. I have the FB app set up and can successfully authenticate against Facebook. Is it possible to use the FB token or generate some sort of key to use to log in to the customer portal?

Thanks

**Comment by perrytew** [comment]
Andrew, 
Based on a separate discussion we had a while back, I'm assuming you've completed this project and moved on a long time ago.  I'm just filling in this question for others who might have the same needs.  We currently don't integrate with Faceback and have no plans to authenticate using their API. 

Thanks.
